apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tester-binding
  namespace: test
  labels:
    env: devstable
subjects:
  - name: tester
    kind: User
    apiGroup: rbac.authorization.k8s.io  # option as it is default value for subjects
roleRef:
  name: tester-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io    # mandatory for roleRef
