apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
    - name: echo-server
      image: jmalloc/echo-server:0.3.6
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "150m"
          memory: "256Mi"
      # liveness probe which checks in every 10s 
      # after the first delay of 5s with request timeout of 3s
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 3
